---
- name: Configurar servidor do banco de dados
  hosts: db-01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db-01"
    - dbusername: "root"
    - dbpassword: "devops"
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql