- name: Upgrade de todos os pacotes do sistema operacional
  apt:
    name: '*'
    state: latest
- name: instalacao do git client
  apt:
    name: 'git'
    state: latest
- name: Configurar hosts lab ansible
  lineinfile:
    dest: /etc/hosts
    line: "{{item}}"
  with_items:
    - 192.168.56.2 control-node
    - 192.168.56.3 app-01
    - 192.168.56.4 db-01